// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgstore

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Bid struct {
	ID        uuid.UUID      `json:"id"`
	ProductID uuid.UUID      `json:"product_id"`
	BidderID  uuid.UUID      `json:"bidder_id"`
	BidAmount pgtype.Numeric `json:"bid_amount"`
	CreatedAt time.Time      `json:"created_at"`
}

type Product struct {
	ID          uuid.UUID      `json:"id"`
	SellerID    uuid.UUID      `json:"seller_id"`
	ProductName string         `json:"product_name"`
	Description pgtype.Text    `json:"description"`
	Baseprice   pgtype.Numeric `json:"baseprice"`
	AuctionEnd  time.Time      `json:"auction_end"`
	IsSold      bool           `json:"is_sold"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Session struct {
	Token  string    `json:"token"`
	Data   []byte    `json:"data"`
	Expiry time.Time `json:"expiry"`
}

type User struct {
	ID           uuid.UUID   `json:"id"`
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	PasswordHash []byte      `json:"password_hash"`
	Bio          pgtype.Text `json:"bio"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}
